POST http://localhost:3000/users
Content-Type: application/json

  {
    "name": "Jerry Seinfeld",
    "email": "Jerry.Seinfeld@test.com",
    "password": "password2",
    "password_confirmation": "password2"
  }

###
POST http://localhost:3000/sessions
Content-Type: application/json
  
  {
    "email": "Jerry.Garcia@test.com",
    "password": "password"
  }  

### 
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE1ODY5MDZ9.vpnNvXrHDeW_P89VHLxLeJ039lxeR6fpZEkM8IRrNR0
Content-Type: application/json